# Generated by Django 2.1.2 on 2018-10-08 18:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cartas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carta', models.CharField(max_length=100, verbose_name='carta')),
                ('efeito', models.BooleanField(verbose_name='efeito')),
                ('cor', models.CharField(max_length=100, verbose_name='cor')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='efeito da carta')),
                ('foto', models.ImageField(upload_to='cartas', verbose_name='foto')),
            ],
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Cartas')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='partida',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User'),
        ),
    ]
